name: Deploy

on:
  push:
    branches: ["master"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: stagecodes
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: stagecodes/osu-mappool-compliance-checker:latest

  deploy:
    name: Deploy
    environment: Production
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p ~/omcc || true
            cd ~/omcc
            echo CLIENT_ID=${{ secrets.CLIENT_ID }} >> .env
            echo CLIENT_SECRET=${{ secrets.CLIENT_SECRET }} >> .env
            echo TOKEN=${{ secrets.TOKEN }} >> .env
            docker stop omcc || true
            docker rm omcc || true
            docker pull stagecodes/omcc:latest
            docker run -d --restart always --name omcc stagecodes/osu-mappool-compliance-checker:latest